version: "2"

run:
  timeout: 3m
  tests: false

linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - predeclared
    - recvcheck
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usetesting
    - wastedassign
  settings:
    dupl:
      threshold: 120
    gocognit:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - commentedOutCode
        - hugeParam
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      severity: error
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: early-return
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: exported
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: var-declaration
        - name: var-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
